# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circesoft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ircesoft.proto\x12\tcircesoft\":\n\x0bPositionECI\x12\r\n\x05X_ECI\x18\x01 \x01(\x01\x12\r\n\x05Y_ECI\x18\x02 \x01(\x01\x12\r\n\x05Z_ECI\x18\x03 \x01(\x01\"=\n\x0bVelocityECI\x12\x0e\n\x06Vx_ECI\x18\x01 \x01(\x01\x12\x0e\n\x06Vy_ECI\x18\x02 \x01(\x01\x12\x0e\n\x06Vz_ECI\x18\x03 \x01(\x01\"\xba\x02\n\rCurrentStatus\x12\x30\n\x10reportedPosition\x18\x01 \x01(\x0b\x32\x16.circesoft.PositionECI\x12\x30\n\x10reportedVelocity\x18\x02 \x01(\x0b\x32\x16.circesoft.VelocityECI\x12\x17\n\x0freportedHeading\x18\x03 \x01(\x01\x12 \n\x18reportedCableRemaining_m\x18\x04 \x01(\x01\x12\'\n\x1freportedPercentBatteryRemaining\x18\x05 \x01(\x01\x12\x11\n\terrorCode\x18\x06 \x01(\x05\x12\x1b\n\x13\x63\x61\x62leDispenseStatus\x18\x07 \x01(\t\x12\x1c\n\x14\x63\x61\x62leDispenseCommand\x18\x08 \x01(\t\x12\x13\n\x0bSequenceNum\x18\t \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'circesoft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITIONECI._serialized_start=30
  _POSITIONECI._serialized_end=88
  _VELOCITYECI._serialized_start=90
  _VELOCITYECI._serialized_end=151
  _CURRENTSTATUS._serialized_start=154
  _CURRENTSTATUS._serialized_end=468
# @@protoc_insertion_point(module_scope)
